# baseURL = "https://shivas.blog/"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

# Author config
[author]
  name = "Shiva Inampudi"
  email = ""
  link = "https://shivas.blog/"
